Add no data screen
filecoin-station/desktop pull request #1711
Opened 2024-07-17 12:58 UTC by davelange

Fixes #1679 

 - Add a warning when there are no records in the selected time range. Display "It seems you have no rewards accrued in the past 7 days | past month | past year | yet"
 - Is there better copy for this?

<img width="1320" alt="Screenshot 2024-07-17 at 13 51 35" src="https://github.com/user-attachments/assets/0cfd5cfc-0431-4b6a-a8ea-693ec21c7439">

2024-07-17 13:00 UTC, juliangruber requested changes

2024-07-17 13:00 UTC, juliangruber commented on renderer/src/pages/dashboard/chart-utils.ts
> +  return `It seems you have no rewards accrued ${ranges[timeRange]}`
I believe we can simply make it static without losing UX:

> It seems you have no rewards accrued in the selected period

2024-07-17 13:57 UTC, juliangruber approved these changes
lgtm, but will want sign off from @patrickwoodhead

2024-07-18 13:34 UTC, patrickwoodhead commented
Please can we change the copy to "You have accrued no rewards in the past x days"?

2024-07-19 11:26 UTC, juliangruber requested changes

2024-07-19 11:26 UTC, juliangruber commented on renderer/src/pages/dashboard/Chart.tsx
> +            It seems you have no rewards accrued in the selected period
```suggestion
            You have accrued no rewards in the selected period
```

2024-07-20 09:12 UTC, merged

2024-07-20 10:13 UTC, juliangruber commented
https://github.com/filecoin-station/desktop/releases/tag/v2.0.6